### ISSUE TITLE
Fitnesse BDD

### ISSUE THREAD

**Issue by telangn** [eviltester/bddexamples#1]
Hi, I was just wondering, when/how are you calling your execute() method in your Fitnesse BDD example?
Thanks!!

**Comment by eviltester** [comment]
I don't call it. Fitnesse calls it. Fitnesses is the one running all the code, I code to Fitnesse conventions.

The documentation might help.

http://www.fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.DecisionTable

**Comment by telangn** [comment]
This can be closed.
